stages:
  - test
  - build

variables:
  SYMFONY_ENV: test
  DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"

cache:
  key: composer
  paths:
    - vendor/
    - var/cache/

before_script:
  - apt-get update && apt-get install -y unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --prefer-dist --no-interaction

test:
  stage: test
  image: php:8.2
  services:
    - postgres:15
  script:
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - vendor/bin/phpunit --testdox
  artifacts:
    reports:
      junit: var/junit.xml
    when: always

build:
  stage: build
  image: node:20
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1h
